name: Build iOS App

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches: [ main ] # Adjust branch name if needed

jobs:
  build:
    name: Build for iOS
    runs-on: macos-latest
    
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache Unity Library folder
      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-

      # Build Unity project for iOS
      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: iOS
          projectPath: '.' # Adjust if Unity project is in subfolder

      # Upload iOS build artifact
      - name: Upload iOS Build
        uses: actions/upload-artifact@v3
        with:
          name: iOS-Build
          path: build/iOS