name: Build iOS App

on:
  workflow_dispatch: # Manual trigger

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest
    
    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache Unity Library folder
      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-

      # Build Unity project for iOS
      - name: Build Unity Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: iOS
          projectPath: '.'

      # Build iOS app with Xcode and create .ipa
      - name: Build iOS App
        uses: yukiarrr/ios-build-action@v1.12.0
        with:
          project-path: build/iOS/Unity-iPhone.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
          workspace-path: build/iOS/Unity-iPhone.xcworkspace

      # Upload final .ipa file
      - name: Upload iOS .ipa
        uses: actions/upload-artifact@v3
        with:
          name: iOS-App
          path: "*.ipa"